2018/11/05 12:23:44 [error] 1383#0: *15444 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /lab/api/build?1541391764712 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/build?1541391764712", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/05 12:26:50 [error] 1383#0: *15497 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /lab/api/build?1541391950725 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/build?1541391950725", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/05 12:35:47 [error] 1383#0: *15656 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /lab/api/build?1541392487218 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/build?1541392487218", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/05 12:48:06 [error] 1383#0: *15816 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /lab/api/build?1541393226444 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/build?1541393226444", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 16:59:29 [error] 1075#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab? HTTP/1.1", upstream: "http://[::1]:8080/lab?", host: "jupyterlab.creat.kim"
2018/11/06 16:59:37 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/static/main.312abdbd100ecf831f55.js HTTP/1.1", upstream: "http://[::1]:8080/lab/static/main.312abdbd100ecf831f55.js", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:01:28 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/settings/@jupyterlab/application-extension:sidebar?1541494888868 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/settings/@jupyterlab/application-extension:sidebar?1541494888868", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:01:28 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/settings/@jupyterlab/katex-extension:plugin?1541494888867 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/settings/@jupyterlab/katex-extension:plugin?1541494888867", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:01:40 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/REPO?1541494900745 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/REPO?1541494900745", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:01:50 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541494910742 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541494910742", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:10 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541494930737 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?1541494930737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:20 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541494940739 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/Library?1541494940739", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:30 [error] 1074#0: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494890028 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494890028", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:30 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494890028 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541494890028", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:30 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541494950737 HTTP/1.1", upstream: "http://localhost/api/contents/?1541494950737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:30 [error] 1074#0: *7 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541494950742 HTTP/1.1", upstream: "http://localhost/api/contents/README?1541494950742", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:30 [error] 1074#0: *49 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/REPO?1541494950745 HTTP/1.1", upstream: "http://localhost/api/contents/REPO?1541494950745", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:33 [error] 1075#0: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494893041 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494893041", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:33 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494893041 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/extensions?1541494893041", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:33 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541494953843 HTTP/1.1", upstream: "http://localhost/lab/api/workspaces/lab?1541494953843", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:35 [error] 1074#0: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494893750 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494893750", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:35 [error] 1074#0: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494893750 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/extensions?1541494893750", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:38 [error] 1074#0: *60 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541494958787 HTTP/1.1", upstream: "http://localhost/api/sessions?1541494958787", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:38 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541494958788 HTTP/1.1", upstream: "http://localhost/api/terminals?1541494958788", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:39 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541494959536 HTTP/1.1", upstream: "http://localhost/lab/api/workspaces/lab?1541494959536", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:39 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541494959785 HTTP/1.1", upstream: "http://localhost/api/contents/Library?1541494959785", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:41 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541494961045 HTTP/1.1", upstream: "http://localhost/lab/api/workspaces/lab?1541494961045", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:42 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541494962166 HTTP/1.1", upstream: "http://localhost/lab/api/workspaces/lab?1541494962166", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:43 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541494963343 HTTP/1.1", upstream: "http://localhost/api/contents/README?content=1&1541494963343", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:46 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab? HTTP/1.1", upstream: "http://[::1]:8080/lab?", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/login?next=%2Flab%3F"
2018/11/06 17:02:49 [error] 1074#0: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/kernelspecs?1541494969424 HTTP/1.1", upstream: "http://[::1]:8080/api/kernelspecs?1541494969424", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:02:58 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541494978053 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541494978053", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:09 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541494989957 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/Library?1541494989957", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:09 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541494989959 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541494989959", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:23 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/untitled.txt?format=text&type=file&content=1&1541495003724 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/untitled.txt?format=text&type=file&content=1&1541495003724", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:23 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/untitled.txt/checkpoints?1541495003767 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/untitled.txt/checkpoints?1541495003767", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:38 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md?content=0&1541495018389 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md?content=0&1541495018389", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:39 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541495019427 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541495019427", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:49 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541495029960 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541495029960", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:50 [error] 1074#0: *49 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494970108 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494970108", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:50 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494970108 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/extensions?1541494970108", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:50 [error] 1074#0: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494970147 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494970147", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:50 [error] 1074#0: *60 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494970147 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541494970147", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:50 [error] 1074#0: *60 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/kernelspecs?1541495030425 HTTP/1.1", upstream: "http://localhost/api/kernelspecs?1541495030425", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:52 [error] 1074#0: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494972551 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541494972551", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:52 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541494972551 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541494972551", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:58 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541495038916 HTTP/1.1", upstream: "http://localhost/api/contents/README?content=1&1541495038916", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541495039425 HTTP/1.1", upstream: "http://localhost/api/sessions?1541495039425", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *60 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541495039428 HTTP/1.1", upstream: "http://localhost/api/terminals?1541495039428", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *60 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541495039955 HTTP/1.1", upstream: "http://localhost/api/contents/?1541495039955", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541495039958 HTTP/1.1", upstream: "http://localhost/api/contents/Library?1541495039958", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *49 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541495039960 HTTP/1.1", upstream: "http://localhost/api/contents/README?1541495039960", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:03:59 [error] 1074#0: *7 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/REPO?1541495039965 HTTP/1.1", upstream: "http://localhost/api/contents/REPO?1541495039965", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:01 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md?content=0&1541495041615 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md?content=0&1541495041615", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:01 [error] 1074#0: *7 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md?content=0&1541495041615 HTTP/1.1", upstream: "http://localhost/api/contents/README/start.md?content=0&1541495041615", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:09 [error] 1074#0: *49 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541495049428 HTTP/1.1", upstream: "http://localhost/api/terminals?1541495049428", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:19 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/static/main.312abdbd100ecf831f55.js HTTP/1.1", upstream: "http://[::1]:8080/lab/static/main.312abdbd100ecf831f55.js", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:21 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?content=1&1541495061975 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?content=1&1541495061975", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:31 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541495071672 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541495071672", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:33 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md/checkpoints?1541495073896 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md/checkpoints?1541495073896", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:42 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md/checkpoints?1541495082200 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md/checkpoints?1541495082200", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:04:52 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541495092737 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?1541495092737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:06 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/start.md?1541495106472 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md?1541495106472", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:06 [error] 1074#0: *60 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md/checkpoints?1541495106499 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md/checkpoints?1541495106499", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:20 [error] 1074#0: *49 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541495120643 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541495120643", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1075#0: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541495122024 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?1541495122024", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1074#0: *7 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495062208 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541495062208", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1074#0: *7 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495062208 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541495062208", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1075#0: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495062280 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541495062280", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495062280 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541495062280", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:22 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/kernelspecs?1541495122672 HTTP/1.1", upstream: "http://localhost/api/kernelspecs?1541495122672", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:25 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541495125660 HTTP/1.1", upstream: "http://localhost/lab/api/workspaces/lab?1541495125660", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:26 [error] 1074#0: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495066383 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541495066383", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:26 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541495066383 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541495066383", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:32 [error] 1074#0: *57 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541495132737 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?1541495132737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:32 [error] 1074#0: *57 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541495132737 HTTP/1.1", upstream: "http://localhost/api/contents/?1541495132737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:32 [error] 1075#0: *50 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541495132739 HTTP/1.1", upstream: "http://localhost/api/contents/Library?1541495132739", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:32 [error] 1074#0: *7 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541495132741 HTTP/1.1", upstream: "http://localhost/api/contents/README?1541495132741", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:05:32 [error] 1075#0: *58 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/REPO?1541495132744 HTTP/1.1", upstream: "http://localhost/api/contents/REPO?1541495132744", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:06:28 [error] 1074#0: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/Ubuntu.md?format=text&type=file&content=1&1541495188520 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/Ubuntu.md?format=text&type=file&content=1&1541495188520", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:06:29 [error] 1075#0: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /api/contents/README/Ubuntu.md/checkpoints?1541495189943 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/Ubuntu.md/checkpoints?1541495189943", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:12:47 [error] 1074#0: *447 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541495567657 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541495567657", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:17:36 [error] 1074#0: *453 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541495856131 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541495856131", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:23:08 [error] 1074#0: *460 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541496188582 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541496188582", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:31:27 [error] 1074#0: *484 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541496687611 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541496687611", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:39:06 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497146976 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497146976", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:39:21 [error] 1468#0: *564 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541497161749 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541497161749", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:39:41 [error] 1468#0: *564 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541497181742 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541497181742", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:01 [error] 1468#0: *564 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541497201741 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?1541497201741", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:11 [error] 1468#0: *546 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497151777 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541497151777", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:11 [error] 1468#0: *546 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497151777 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541497151777", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:11 [error] 1468#0: *530 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497151819 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541497151819", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:11 [error] 1468#0: *530 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497151819 HTTP/1.1", upstream: "http://localhost/lab/api/extensions?1541497151819", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:14 [error] 1468#0: *548 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497154755 HTTP/1.1", upstream: "http://127.0.0.1:8080/lab/api/extensions?1541497154755", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:14 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/api/extensions?1541497154755 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/extensions?1541497154755", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:21 [error] 1468#0: *530 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/Library?1541497221739 HTTP/1.1", upstream: "http://localhost/api/contents/Library?1541497221739", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:21 [error] 1468#0: *548 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/?1541497221737 HTTP/1.1", upstream: "http://localhost/api/contents/?1541497221737", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:21 [error] 1468#0: *546 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?1541497221741 HTTP/1.1", upstream: "http://localhost/api/contents/README?1541497221741", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:21 [error] 1468#0: *536 no live upstreams while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/REPO?1541497221744 HTTP/1.1", upstream: "http://localhost/api/contents/REPO?1541497221744", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:40:46 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541497246539 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541497246539", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:41:01 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497261081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497261081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:41:14 [error] 1468#0: *536 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541497274401 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541497274401", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:41:26 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497286464 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497286464", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:41:37 [error] 1468#0: *536 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497297913 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497297913", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:41:51 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497311081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497311081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:42:10 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/start.md?1541497330881 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md?1541497330881", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:42:22 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497342578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497342578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:42:33 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/start.md/checkpoints?1541497353158 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md/checkpoints?1541497353158", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:42:49 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/start.md?1541497368997 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/start.md?1541497368997", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:43:01 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497381081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497381081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:43:21 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497401081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497401081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:43:42 [error] 1468#0: *530 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497422577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497422577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:43:59 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497439108 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497439108", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:44:12 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497452577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497452577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:44:31 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497471081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497471081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:44:45 [error] 1468#0: *536 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497485786 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497485786", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:03 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497503577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497503577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:17 [error] 1468#0: *548 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541497517111 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541497517111", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:30 [error] 1468#0: *546 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497530441 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497530441", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:41 [error] 1469#0: *982 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497541081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497541081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:42 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497542723 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497542723", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:55 [error] 1469#0: *982 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/Ubuntu.md/checkpoints?1541497555198 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/Ubuntu.md/checkpoints?1541497555198", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:45:55 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /lab/static/1.4975b6988a585038ac03.js HTTP/1.1", upstream: "http://[::1]:8080/lab/static/1.4975b6988a585038ac03.js", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:46:11 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497571081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497571081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:46:31 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497591577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497591577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:46:47 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/README.md?format=text&type=file&content=1&1541497607841 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/README.md?format=text&type=file&content=1&1541497607841", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:47:02 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541497622907 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541497622907", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:47:21 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541497641075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541497641075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:47:41 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497661081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497661081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:48:02 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497682597 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497682597", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:48:20 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541497700445 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541497700445", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:48:32 [error] 1468#0: *1102 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497712577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497712577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:48:45 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541497725970 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541497725970", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:48:58 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541497738557 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541497738557", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:49:11 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541497751297 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541497751297", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:49:26 [error] 1468#0: *981 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497766789 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497766789", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:49:41 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497781081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497781081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:50:01 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497801081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497801081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:50:21 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497821578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497821578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:50:41 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497841081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497841081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:51:01 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497861081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497861081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:51:21 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497881081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497881081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:51:41 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541497901075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541497901075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:01 [error] 1468#0: *1012 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541497921075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541497921075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:11 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497931081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497931081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:16 [error] 1468#0: *1240 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /api/contents/README/internet.md/checkpoints?1541497936587 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541497936587", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:31 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541497951090 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541497951090", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:48 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541497968388 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541497968388", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:52:48 [error] 1468#0: *1240 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md/checkpoints?1541497968826 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541497968826", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:53:01 [error] 1468#0: *1303 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541497981066 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541497981066", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:53:01 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541497981396 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541497981396", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:53:21 [error] 1468#0: *1240 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498001081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498001081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:53:37 [error] 1468#0: *1303 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541498017023 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541498017023", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:53:47 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498027578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498027578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:54:01 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498041075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498041075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:54:11 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498051075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498051075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:54:31 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498071088 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498071088", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:54:41 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498081081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498081081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:01 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498101075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498101075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:09 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541498109175 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541498109175", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:30 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498130577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498130577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:31 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498131081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498131081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:44 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541498144856 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541498144856", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:55:51 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498151074 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498151074", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:56:11 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498171082 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498171082", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:56:21 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498181081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498181081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:56:28 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/kernelspecs?1541498188075 HTTP/1.1", upstream: "http://[::1]:8080/api/kernelspecs?1541498188075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:56:51 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498211074 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498211074", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:56:51 [error] 1468#0: *1232 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498211081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498211081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:57:11 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498231578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498231578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:57:13 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541498233018 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541498233018", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:57:25 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498245517 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498245517", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:57:25 [error] 1469#0: *1233 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541498245922 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541498245922", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:57:51 [error] 1468#0: *1456 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498271075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498271075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:58:11 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498291081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498291081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:58:22 [error] 1468#0: *1456 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /api/contents/README/internet.md/checkpoints?1541498302014 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541498302014", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:58:41 [error] 1468#0: *1456 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498321081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498321081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:59:01 [error] 1468#0: *1456 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498341081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498341081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:59:13 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498353720 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498353720", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:59:31 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498371075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498371075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 17:59:51 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498391081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498391081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:00:07 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md/checkpoints?1541498407946 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541498407946", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:00:21 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498421157 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498421157", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:00:34 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /api/contents/README/internet.md?1541498434958 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?1541498434958", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:00:51 [error] 1468#0: *1695 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498451081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498451081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:01:31 [error] 1468#0: *1695 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498491554 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498491554", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:01:43 [error] 1468#0: *1458 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498503424 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498503424", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:01:58 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541498518604 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541498518604", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:02:15 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498535578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498535578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:02:31 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498551082 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498551082", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:02:51 [error] 1468#0: *1552 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498571081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498571081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:04:35 [error] 1469#0: *1797 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498675578 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498675578", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:04:51 [error] 1469#0: *1797 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498691075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498691075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:04:55 [error] 1468#0: *1803 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "POST /api/contents/?1541498695370 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/?1541498695370", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:05:12 [error] 1468#0: *1824 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541498712500 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541498712500", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:05:31 [error] 1468#0: *1824 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541498731082 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541498731082", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:05:34 [error] 1469#0: *1797 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498734175 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498734175", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:06:23 [error] 1469#0: *1797 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?format=text&type=file&content=1&1541498783710 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?format=text&type=file&content=1&1541498783710", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:06:23 [error] 1468#0: *1803 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md/checkpoints?1541498783801 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541498783801", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:06:41 [error] 1469#0: *1797 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541498801075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541498801075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:09:47 [error] 1468#0: *1888 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541498986724 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541498986724", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:10:31 [error] 1468#0: *1888 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499031086 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499031086", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:10:51 [error] 1468#0: *1888 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541499051075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541499051075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:11:11 [error] 1468#0: *1894 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499071081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499071081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:11:31 [error] 1468#0: *1894 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499091081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499091081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:11:51 [error] 1468#0: *1888 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541499111075 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541499111075", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:18:18 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541499498577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541499498577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:18:35 [error] 1468#0: *1965 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541499515387 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541499515387", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:18:47 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md/checkpoints?1541499527779 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md/checkpoints?1541499527779", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:19:01 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499541080 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499541080", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:19:31 [error] 1468#0: *1965 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499571611 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499571611", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:19:51 [error] 1468#0: *1965 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/kernelspecs?1541499591077 HTTP/1.1", upstream: "http://[::1]:8080/api/kernelspecs?1541499591077", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:20:11 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499611081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499611081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:20:31 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499631081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499631081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:20:51 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499651081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499651081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:21:11 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README?content=1&1541499671577 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README?content=1&1541499671577", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:21:31 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499691080 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499691080", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:21:51 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499711081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499711081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:22:11 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499731081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499731081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:22:26 [error] 1468#0: *1965 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "PUT /lab/api/workspaces/lab?1541499746409 HTTP/1.1", upstream: "http://[::1]:8080/lab/api/workspaces/lab?1541499746409", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:22:45 [error] 1468#0: *1965 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/contents/README/internet.md?content=0&1541499765639 HTTP/1.1", upstream: "http://[::1]:8080/api/contents/README/internet.md?content=0&1541499765639", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:23:01 [error] 1468#0: *1961 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/sessions?1541499781074 HTTP/1.1", upstream: "http://[::1]:8080/api/sessions?1541499781074", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
2018/11/06 18:25:31 [error] 1468#0: *2104 connect() failed (111: Connection refused) while connecting to upstream, client: 220.115.183.132, server: jupyterlab.creat.kim, request: "GET /api/terminals?1541499931081 HTTP/1.1", upstream: "http://[::1]:8080/api/terminals?1541499931081", host: "jupyterlab.creat.kim", referrer: "https://jupyterlab.creat.kim/lab?"
